### ISSUE TITLE
After adding config the home assistant started as safe mode

### ISSUE THREAD

**Issue by mnayef95** [Misiu/argon40#11]
```
  - platform: command_line
    name: CPU Temp
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: "{{ value | multiply(0.001) | round(1) }}"
```

I have added this configuration to the `configuration.yaml` directly, and after that, the home assistant started as safe mode

**Comment by Misiu** [comment]
@mnayef95 what version of HA are you using?
In 0.116 processor_temperature was added to systemmonitor, so you can use that integration instead.
https://www.home-assistant.io/integrations/systemmonitor/
