### ISSUE TITLE
Can’t find argon fan in HASSIO

### ISSUE THREAD

**Issue by s3oud333** [Misiu/argon40#13]
I tried installing it throw copying and pasting and also in HASC but doesn't seems to showing at all 
Please help

**Comment by Misiu** [comment]
Sorry for the late reply.
Did you solve your problem?

**Comment by s3oud333** [comment]
No worries thanks for responding, I figure out the issue, I have to remove memory card to edit as you described in some forum to enable the i2c , so Keep the awesome work and I'll wait for upgrade :)
