### ISSUE TITLE
Hey just wondering

### ISSUE THREAD

**Issue by s3oud333** [Misiu/argon40#16]
Hey , I finally got the argo40 to perfectly work with homeassistant thanks to ( remove usb and edit the file) method. So do u have a card to adjust the speed, on/off of the fan , is there is a way to know the status of fan , on/off , speed in HomeKit 
I know I might sound dum, but I learn from you and other creative people :)

**Comment by Misiu** [comment]
@s3oud333 sadly not now. The current implementation of the fan component only supports a list of speed, I need to have support for percentage value. There was a PR in the Core repo: https://github.com/home-assistant/core/pull/39204 but the author didn't have time to complete it.
The current workaround is to have a binary sensor (https://www.home-assistant.io/integrations/binary_sensor/) and an input number (https://www.home-assistant.io/integrations/input_number/). This way when you set fan speed via the automation you can set those two values (on/off and speed) and display them on a card. Another automation could be used to update the speed when you update input value, but I think speed based on CPU temperature is more useful.
