### ISSUE TITLE
can't find the service argon40.set_fan_speed

### ISSUE THREAD

**Issue by maobuz** [Misiu/argon40#29]
Hi argon40 team,
i'm trying yo install your component but, following the installation guide, i can't find the service argon40.set_fan_speed

Can you check compatibility with version | core-2021.9.4 (and.5) ?

Please let me know, thank you.

step:

configuration.yaml

![image](https://user-images.githubusercontent.com/73724063/132678917-8d7e561d-3dee-4396-808d-9095c317027a.png)

custom_component

![image](https://user-images.githubusercontent.com/73724063/132679122-4766efba-3657-42fd-8a78-64eb43af7d1d.png)

restart HA and

![image](https://user-images.githubusercontent.com/73724063/132679224-43ad39e0-8c8e-4397-b20d-96fa9134e845.png)

not log problem 

![image](https://user-images.githubusercontent.com/73724063/132679293-157d91fd-0be4-468e-b04a-2575b1710610.png)

2021-09-09 13:34:56 ERROR (MainThread) [homeassistant.setup] Setup failed for argon40: Integration failed to initialize.
2021-09-09 13:34:56 ERROR (Thread-2) [root] Uncaught thread exception

**Comment by C0pywriting** [comment]
-> [Lösung](https://github.com/Misiu/argon40/issues/28)

issue can be closed
