### ISSUE TITLE
No argon40 integration in core-2021.11.3

### ISSUE THREAD

**Issue by thierry-rhone** [Misiu/argon40#30]
Hi,
core-2021.11.3
supervisor-2021.10.8

I have copied argon40 folder from master branch
So I have the 4 files
custom_components/argon40/__init__.py
custom_components/argon40/const.py
custom_components/argon40/manifest.json
custom_components/argon40/services.yaml

I restarted home assistant twice, clear navigator cache but I don't have any argon integration in configuration add integration.

It is a compatibility problem ?

**Comment by Misiu** [comment]
I think not. Did you add entry to configuration.yaml? It is needed because for now my component doesn't support config flow.

**Comment by thierry-rhone** [comment]
Thank for your answer...
I added argon40: in my configuration.yaml, (and sensor and automation)
I have the message ::
The following integrations and platforms could not be set up:    argon40

**Comment by Misiu** [comment]
You must enable I2C. This is the reason for that, message.

**Comment by thierry-rhone** [comment]
It's ok with I2C
Thank's

**Comment by Marie-Isere** [comment]
even if I no longer have the message "The following integrations and platforms could not be set up: argon40", when I call the set service in the development tools with data 40, I have this result

![image](https://user-images.githubusercontent.com/94218939/141822394-747a9ae6-a913-4bd7-9883-69524f929c85.png)

**Comment by thierry-rhone** [comment]
even if I no longer have the message "The following integrations and platforms could not be set up: argon40", when I call the set service in the development tools with data 40, I have this result
(fan speed don't change)

![image](https://user-images.githubusercontent.com/94218939/141822394-747a9ae6-a913-4bd7-9883-69524f929c85.png)

**Comment by Misiu** [comment]
@thierry-rhone try putting:
```
speed: 40
```
as service data.
This should do the trick.

**Comment by thierry-rhone** [comment]
Thank you
