### ISSUE TITLE
Invalid config 

### ISSUE THREAD

**Issue by maobuz** [Misiu/argon40#34]
The following integrations and platforms could not be set up:

[argon40](https://github.com/Misiu/argon40) ([Show logs](https://xxxxxxxxxxxxxxxxxxxxxxxx.org/config/logs?filter=argon40))
Please check your config and [logs](https://xxxxxxxxxxxxxxxxxxxxxxs.org/config/logs).

Logger: homeassistant.setup
Source: setup.py:162
First occurred: 12:20:39 (1 occurrences)
Last logged: 12:20:39

Setup failed for custom integration argon40: Requirements for argon40 not found: ['RPi.GPIO==0.7.1a4'].

Home Assistant 2022.7.6
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.1 - latest

**Comment by Misiu** [comment]
Hi, this is a possible duplicate of https://github.com/Misiu/argon40/issues/32.
It should be fixed in the latest version - https://github.com/Misiu/argon40/releases/tag/0.0.5
If you use HACS an update should show, if not download argon.zip and extract to `custom_components/argon40` directory
