### ISSUE TITLE
Error Loading Argon40 - HA startup

### ISSUE THREAD

**Issue by upsidedown76** [Misiu/argon40#56]
I use HA 2023.10.3 core installation on a PI4.

I did all the necessary steps - i2c is activated - checked in terminal and as well downloaded the i2c configurated which told me that i2c is activated. here results from terminal:
# lsmod | grep i2c
i2c_dev                20480  2
i2c_mux_pinctrl        16384  0
i2c_mux                16384  1 i2c_mux_pinctrl
i2c_bcm2835            16384  1

## Configuration

```yaml

Add your logs here.

This error originated from a custom integration.

Logger: custom_components.argon40
Source: custom_components/argon40/__init__.py:73
Integration: argon40 (documentation, issues)
First occurred: 21:54:03 (1 occurrences)
Last logged: 21:54:03

Bad logger message: Error %d, %s accessing 0x%02X: Check your I2C address ((None, None, 26))
Traceback (most recent call last):
  File "/config/custom_components/argon40/__init__.py", line 73, in async_setup
    bus.write_byte(I2C_ADDRESS, 26)
  File "/usr/local/lib/python3.11/site-packages/smbus/util.py", line 59, in validator
    return fn(*args, **kwdefaults)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/smbus/smbus.py", line 121, in write_byte
    raise IOError(ffi.errno)
OSError: 121

**Comment by Misiu** [comment]
Hi @upsidedown76,
sorry to hear you have problems using my integration.
I'm not aware of any problems with the recent versions of Home Assistant.
Which method of activating I2C did you use?
Do you have other I2C devices connected to your PI?

**Comment by upsidedown76** [comment]
Hi,

I think I did it finally with the i2c configurator. And I have a external
hard drive mounted on one of the usb - but not sure if this has anything to
do with i2c. Am still a rookie with raspberry pi.

Best, Oliver

Am Mo., 30. Okt. 2023 um 08:54 Uhr schrieb Tomasz ***@***.***

**Comment by Misiu** [comment]
@upsidedown76,

so if I understand correctly, the issue is fixed and you can use the integration? If yes, then please close the issue.



> Am still a rookie with raspberry pi.

Same here :)

**Comment by upsidedown76** [comment]
nope, sorry not to being clear - I finally did the i2c with the i2c
configurator add on.

I still have the same error. Do you use the Argon Fan Hat or do you use
Argon One?

Best,

Oliver

Am Mo., 30. Okt. 2023 um 10:18 Uhr schrieb Tomasz ***@***.***

**Comment by Misiu** [comment]
Hi,
I used Argon One V2 case (https://argon40.com/products/argon-one-v2-case-for-raspberry-pi-4).
Sadly I don't have access to HAT or the new M2 case. Maybe the address of the FAN changed.
Can you try Raspbian and the official script?
Copy can be found here: https://github.com/okunze/Argon40-ArgonOne-Script

**Comment by upsidedown76** [comment]
Hi Tomasz,

I tired the Argon One plugin and that unfortunately does not work either.
As your instructions said that it works with the Fan Hat I was very happy
about it. So guess its not working. How do I find out the address of the
fan? Am happy to play around with the script, but need some help ;).

Best,

Oliver

Am Mo., 30. Okt. 2023 um 12:53 Uhr schrieb Tomasz ***@***.***

**Comment by Misiu** [comment]
you can try to contact Argon40 for help.
If I remember correctly both the case and the fan has the same address.
My case had some instructions inside the box.

You can try i2c-tools:
https://learn.adafruit.com/scanning-i2c-addresses/raspberry-pi

**Comment by upsidedown76** [comment]
Thanks a lot! I only have the fan, not the case.

Best, Oliver

Am Mo., 30. Okt. 2023 um 14:54 Uhr schrieb Tomasz ***@***.***

**Comment by upsidedown76** [comment]
And i found a device on 50. But no clue where to amend this in your script.
Tried in line 73, but no success.

Best, Oliver

Am Mo., 30. Okt. 2023 um 14:56 Uhr schrieb Oliver Kueng <
***@***.***>:

**Comment by Misiu** [comment]
Try https://github.com/Misiu/argon40/blob/master/custom_components/argon40/__init__.py#L29
You should change 0x1A to 0x50 or 0x32 (not sure if results from i2c are in dec or hex)

**Comment by Misiu** [comment]
Could you please add a picture of the hat or post a link to the product (HAT)?

**Comment by upsidedown76** [comment]
Hi Tomasz,

Attached a picture (front and back) as well as a screenshot of the error
log in HA. This one I did not post in Github.

Best, Oliver

Am Mo., 30. Okt. 2023 um 15:05 Uhr schrieb Tomasz ***@***.***

**Comment by Misiu** [comment]
Could you please reply using GitHub?
When replying via email no attachments are added.

**Comment by upsidedown76** [comment]
images included now
![Homeassistant_error_log](https://github.com/Misiu/argon40/assets/133035827/55aae6cb-436e-44d2-9ec5-8bdf890394a1)
![argon_fan_hat_front](https://github.com/Misiu/argon40/assets/133035827/e31ee6c5-e3d4-4d28-99b8-4eb1600e691b)
![argon_Fan_hat_back](https://github.com/Misiu/argon40/assets/133035827/97c767fd-9f2e-42d9-939d-82ddd92fdcb7)

**Comment by upsidedown76** [comment]
and here what i get when I go into root in terminal and then - it seems that i2c should be ok.
cd /dev 
ls
![Screenshot from 2023-10-30 16-47-31](https://github.com/Misiu/argon40/assets/133035827/980d8650-7f72-423d-9cca-564362388449)

**Comment by Misiu** [comment]
I just contacted Argon40 and they confirmed that they are still using the I2C address and codes from https://github.com/Argon40Tech/Argon-ONE-i2c-Codes
When I started developing this integration, the first thing I did was run the official Raspberry Pi OS (https://www.raspberrypi.com/software/) and use the official script from Argon40 (instructions should be in the box). Then when I confirmed that the case (or HAT in your case) works I switched to HA.
Did you try Pi OS? This way you will be sure that the HAT is working.

**Comment by upsidedown76** [comment]
thanks a lot. I did not try Pi OS yet. Will do and let you know if it
works.

Am Di., 31. Okt. 2023 um 08:09 Uhr schrieb Tomasz ***@***.***

**Comment by Misiu** [comment]
@upsidedown76 any updates?

**Comment by Misiu** [comment]
let us keep this open until your issue is solved.
Thanks for the update
