### ISSUE TITLE
Double tap is spamming

### ISSUE THREAD

**Issue by MyRandomUsername** [Misiu/argon40#6]
## Version of the custom_component
VERSION = "0.0.1"

hassOS 5.2 on rpi 4.

## Configuration
argon40:

## Describe the bug
I setup the sample automation of creating a notification with the double tap of the power button.  For some reason this is triggering every minute even when the power button is not being pressed.  If I use a different OS (different usb stick) and the provided Argon40 script it detects and reacts normally to power buttons so doesn't seem to be a physical/connection issue.

**Comment by Misiu** [comment]
It might be something with the new OS.
I'm still using the old one, but give me some time and I'll try this on OS 5.2. I'm waiting for SSD drive, so when it arrives I'll update to 5.2
