### ISSUE TITLE
Support for newer cases (Argon NEO 5 BRED, Argon One v3)

### ISSUE THREAD

**Issue by eikowagenknecht** [Misiu/argon40#75]
Is support for the newer Raspberry Pi 5 cases planned? Like the [Argon NEO 5 BRED](https://argon40.com/products/argon-neo-case-for-raspberry-pi-5) or [Argon ONE V3](https://argon40.com/products/argon-one-v3-case-for-raspberry-pi-5)?

**Comment by Misiu** [comment]
@eikowagenknecht Yes, I plan to add support for ONE V3, it arrived to me a couple of days ago.
I'll get you updated as soon as I set dev env and have working version

**Comment by Misiu** [comment]
@eikowagenknecht I've created new branch for Pi5 and Argon ONE V3 - https://github.com/Misiu/argon40/tree/pi5
I have the exact same case and the changes I applied in that branch work just fine.

When you use HassOS I2C Configurator remember to disable `Protection mode` and to do a hard restart (unplug the PI from power) twice.
You must get those lines in the addon logs:
![image](https://github.com/user-attachments/assets/7fc2e797-50cc-4817-a70c-b208548b29df)

**Comment by eikowagenknecht** [comment]
Thank you!

**Comment by Misiu** [comment]
@eikowagenknecht please confirm that the code works on your PI5 and with your case.
I have PI5 dev env and I'm setting PI4, I just need the PI4 to arrive.
I plan to rewrite the integration to have config flow and to expose the case fan as a fan in HA.
