### ISSUE TITLE
HA restart with automation speed_fan = 0

### ISSUE THREAD

**Issue by McFlyPartages** [Misiu/argon40#8]
Hello,

Thank you for your integration which is very useful.

HA 0.114.4
rpi4 4GB
HassOS 4.13
Supervisor 244
I have a problem when I run the following home assistant automation restart.

Automation is as follows.
- id: '1600262958937'
   alias: RPi fan_speed OFF
   trigger:
   - below: '40'
     entity_id: sensor.rpi_cpu_temperature
     for: '1'
     platform: numeric_state
   condition: []
   action:
   - data:
       speed: 0
     service: argon40.set_fan_speed
   mode: single

When I run it my system reboots.

Do you have the same problem where it comes from me.

thank you in advance log

```text

Add your logs here.

```

**Comment by ranomier** [comment]
I have the same problem
